name: "Safe Service Sync"
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Safe Service Sync"
        uses: rmeissner/safe-service-monitor-gh-action@main
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          safe-address: ${{ secrets.TARGET_SAFE }}
          service-url: ${{ secrets.SERVICE_URL }}